// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("http://localhost:8083/")
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    await driver.findElement(By.id("openModalBtn")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("VisakhMadathil")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("madathil")
    await driver.findElement(By.id("modal-btn")).click()
  })
})
